apiVersion: v1
kind: Service
metadata:
  name: mds-nodeport-service
  namespace: confluent
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 32200
      protocol: TCP
  selector:
    app: kafka